name: Hello world

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: |
          echo "Hello world"
          env
      - name: Getting the Run URL
        run: |
          echo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"

      - name: fail
        run: exit 2
      - name: Success
        if: success()
        run: echo "SUCCESS"
      - name: Failure
        if: failure()
        run: echo "FAILURE"
